# Basic
name:               "Daniel Duan"
description:        "Daniel Duan's Thoughts And Works."

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
url:                "https://duan.ca"
author:             "Daniel Duan"
twitter:
  username:         "daniel_duan"

# URL
baseurl:            ""
permalink:          /:year/:month/:day/:title/

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "articles"
    href:           "/articles"
  - name:           "videos"
    href:           "https://www.youtube.com/channel/UCkBVC0dMgyUnxzettP7qE-A"
  - name:           "Links"
    href:           "/links"
  - name:           "Projects"
    href:           "/projects"
  - name:           "About"
    href:           "/about"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
      master:       true
  -
    scope:
      path:         ""
      type:         links
    values:
      layout:       "link"
      master:       true

tag_page_layout: tag
tag_page_dir: tag

tag_feed_layout: tagfeed
tag_feed_dir: tag

tag_permalink_style: pretty

collections:
    links:
        output: true
        permalink: /linked/:year/:month/:title/

plugins:
  - jekyll-seo-tag
